# Generated by Django 5.2.8 on 2025-12-11 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisPayement',
            fields=[
                ('idavispayement', models.AutoField(primary_key=True, serialize=False)),
                ('montant', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('avance', models.CharField(max_length=100)),
                ('dateavance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastre',
            fields=[
                ('idcadastre', models.BigAutoField(primary_key=True, serialize=False)),
                ('registre', models.CharField(max_length=150)),
                ('folio', models.CharField(max_length=150)),
                ('section', models.CharField(max_length=150)),
                ('dite', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=150)),
                ('parcelle', models.CharField(max_length=150)),
                ('libcadastre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('identite', models.AutoField(primary_key=True, serialize=False)),
                ('libentite', models.CharField(max_length=150)),
                ('abrev', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='entites/')),
                ('sigle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('idoperation', models.AutoField(primary_key=True, serialize=False)),
                ('liboperation', models.CharField(max_length=150)),
                ('cout', models.CharField(max_length=100)),
                ('sigle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('idpersonne', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('cin', models.CharField(max_length=50)),
                ('datecin', models.CharField(max_length=50)),
                ('lieucin', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('infostatut', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('idtitre', models.AutoField(primary_key=True, serialize=False)),
                ('libtitre', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopoDom',
            fields=[
                ('idtopdom', models.AutoField(primary_key=True, serialize=False)),
                ('litopdom', models.CharField(max_length=150)),
                ('direction', models.CharField(max_length=150)),
                ('photo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAgent',
            fields=[
                ('idtype', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('idtypeoperation', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('idagent', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('mdp', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('sigleAg', models.CharField(max_length=50)),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.entite')),
                ('idtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.typeagent')),
            ],
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('idindice', models.AutoField(primary_key=True, serialize=False)),
                ('indice', models.CharField(max_length=150)),
                ('commune', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.entite')),
            ],
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('idquittance', models.AutoField(primary_key=True, serialize=False)),
                ('refquittance', models.CharField(max_length=150)),
                ('montant', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('topdom', models.CharField(max_length=150)),
                ('avance', models.CharField(max_length=100)),
                ('reste', models.CharField(max_length=100)),
                ('refdossier', models.CharField(max_length=150)),
                ('bureau', models.CharField(max_length=150)),
                ('requisition', models.CharField(max_length=150)),
                ('idagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.agent')),
                ('idavispayement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.avispayement')),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.entite')),
            ],
        ),
        migrations.CreateModel(
            name='QuiCadastre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcadastre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.cadastre')),
                ('idquittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.quittance')),
            ],
        ),
        migrations.CreateModel(
            name='OpQuittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.CharField(max_length=100)),
                ('nb', models.CharField(max_length=50)),
                ('pu', models.CharField(max_length=50)),
                ('idoperation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.operation')),
                ('idquittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.quittance')),
            ],
        ),
        migrations.CreateModel(
            name='QuittancePersonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typepersonne', models.CharField(max_length=50)),
                ('idpersonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.personne')),
                ('idquittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.quittance')),
            ],
        ),
        migrations.CreateModel(
            name='QuiTitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idquittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.quittance')),
                ('idtitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.titre')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='idtopdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.topodom'),
        ),
        migrations.AddField(
            model_name='entite',
            name='idtopdom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.topodom'),
        ),
        migrations.AddField(
            model_name='operation',
            name='idtypeoperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grecapp.typeoperation'),
        ),
    ]
