# Generated by Django 5.2.8 on 2025-12-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grecapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topodom',
            name='photo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
